### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by ghost** [UBC-MDS/525_group7#10]
Great work!
Please make sure to justify why there are only three contributors to the github repo

**Comment by athy9193** [comment]
Hi @paul-TA , thank you :) 

We mentioned it in the notebook under the comparison section (as shown in the picture below). In specific, Rahul moved to Vancouver during the week of Milestone 1. We had allocated tasks to all members on Tuesday but unfortunately, on Friday, Rahul informed us the he did not have a suitable laptop adapter to finish his work. Given the time constraints and the fact that only one of our members has a 16GB machine that can run the `rpy2` package, the rest of the group decided to take over and completed Rahul's work. He said he will contribute for subsequent milestones.
Hope that clarifies.

![image](https://user-images.githubusercontent.com/56498756/114449125-42e41200-9b89-11eb-807d-bee271cfef7f.png)
